// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accountTblFieldNames          = builder.RawFieldNames(&AccountTbl{}, true)
	accountTblRows                = strings.Join(accountTblFieldNames, ",")
	accountTblRowsExpectAutoSet   = strings.Join(stringx.Remove(accountTblFieldNames), ",")
	accountTblRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(accountTblFieldNames, "id"))
)

type (
	accountTblModel interface {
		Insert(ctx context.Context, data *AccountTbl) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AccountTbl, error)
		Update(ctx context.Context, data *AccountTbl) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAccountTblModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AccountTbl struct {
		Id           int64          `db:"id"`
		Username     string         `db:"username"`
		HashPassword string         `db:"hash_password"`
		Role         int64          `db:"role"`
		Name         string         `db:"name"`
		Email        sql.NullString `db:"email"`
		Phone        sql.NullString `db:"phone"`
		AvataUrl     sql.NullString `db:"avata_url"`
		Birthday     sql.NullString `db:"birthday"`
	}
)

func newAccountTblModel(conn sqlx.SqlConn) *defaultAccountTblModel {
	return &defaultAccountTblModel{
		conn:  conn,
		table: `"public"."account_tbl"`,
	}
}

func (m *defaultAccountTblModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAccountTblModel) FindOne(ctx context.Context, id int64) (*AccountTbl, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", accountTblRows, m.table)
	var resp AccountTbl
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountTblModel) Insert(ctx context.Context, data *AccountTbl) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, accountTblRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Username, data.HashPassword, data.Role, data.Name, data.Email, data.Phone, data.AvataUrl, data.Birthday)
	return ret, err
}

func (m *defaultAccountTblModel) Update(ctx context.Context, data *AccountTbl) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, accountTblRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Username, data.HashPassword, data.Role, data.Name, data.Email, data.Phone, data.AvataUrl, data.Birthday)
	return err
}

func (m *defaultAccountTblModel) tableName() string {
	return m.table
}
